### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by pemaxim** [UsabilityDynamics/node-docker-gce-discovery#4]
```
0|app      | TypeError: Cannot read property 'Id' of undefined
0|app      |     at /opt/sources/MyPropertyOffice/mpo-app/node_modules/docker-gce-discovery/index.js:113:26
0|app      |     at arrayEach (/opt/sources/MyPropertyOffice/mpo-app/node_modules/docker-gce-discovery/node_modules/lodash/lodash.js:537:11)
0|app      |     at Function.forEach (/opt/sources/MyPropertyOffice/mpo-app/node_modules/docker-gce-discovery/node_modules/lodash/lodash.js:9351:14)
0|app      |     at DockerEvents.<anonymous> (/opt/sources/MyPropertyOffice/mpo-app/node_modules/docker-gce-discovery/index.js:112:13)
0|app      |     at DockerEvents.emit (events.js:107:17)
0|app      |     at JSuck.<anonymous> (/opt/sources/MyPropertyOffice/mpo-app/node_modules/docker-gce-discovery/node_modules/docker-events/index.js:34:12)
0|app      |     at JSuck.emit (events.js:107:17)
0|app      |     at readableAddChunk (_stream_readable.js:163:16)
0|app      |     at JSuck.Readable.push (_stream_readable.js:126:10)
0|app      |     at JSuck.Transform.push (_stream_transform.js:140:32)
```

![image](https://cloud.githubusercontent.com/assets/308489/20563696/50ca6206-b192-11e6-911e-9a9d003c87d9.png)

**Comment by kavaribes** [comment]
Added some fixes.

**Comment by pemaxim** [comment]
Looks good. @kavaribes could you please double check the stuff and push new release? Thanks

**Comment by andypotanin** [comment]
Closing, abandoned.
